project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    publish:
  - quarto-pub:
      id: "nithura-t"
      site: "my-first-website"



